version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    networks:
      - monitoring

  nginx-exporter:
    image: nginx/nginx-prometheus-exporter:latest
    ports:
      - "9113:9113"
    networks:
      - monitoring
    command: ["-nginx.scrape_uri=http://nginx:80/stub_status"]

networks:
  monitoring:
    driver: bridge


